# Generated by Django 4.1.3 on 2023-10-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=65)),
                ('uv', models.SmallIntegerField(max_length=1)),
            ],
        ),
    ]
